# Inspired by https://github.com/yeasy/docker-compose-files/blob/master/mongo-elasticsearch/docker-compose.yml
#
# This will start 5 nodes:
# mongo will server as the only member of the cluster
# mongosetup will init mongo as the master node
# elasticsearch will server as the index search db
# mongo-connector will pipeline mongodb content to the elasticsearch
version: "3"

services:
  mongo:
    image: mongo:3.4
    # hostname: mongo
    # mem_limit: 1024m
    environment:
      - TZ=Europe/Paris
    expose:
      - "27017:27027"
      - "28017:28027"
    restart: always
    # entrypoint: [ "/usr/bin/mongod", "--dbpath", "/database", "--replSet", "rs", "--httpinterface", "--rest" ]
    volumes:
      - ./database:/database

  mongosetup:
    build: ./db_config/mongosetup
    # mem_limit: 1024m
    links:
      - mongo:mongo
    depends_on:
      - mongo


  elasticsearch:
    image: elasticsearch:1.7
    # mem_limit: 1024m
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
      - "9300"

  mongoconnector:
    build: ./db_config/mongoconnect
    links:
      - elasticsearch:elasticsearch
      - mongo:mongo
    depends_on:
      - elasticsearch
      - mongo

  web:
    build: .
    environment:
      - TZ=Europe/Paris
    ports:
      - "8011:8011"
    restart: always
    links:
      - elasticsearch:elasticsearch
      - mongo:mongo
    depends_on:
      - elasticsearch
      - mongo

networks:
  default:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
          # - gateway: 10.5.0.1
